# Generated by Django 3.1.5 on 2021-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
