# Generated by Django 3.1.5 on 2021-02-14 09:34

import auth_system.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='profile_pics/user-1.jpg', storage=auth_system.storage.OverwriteStorage, upload_to=auth_system.storage.upload_image_path)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('birthdate', models.CharField(blank=True, max_length=30)),
                ('activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
